# Set log level to INFO (default)
logging.level.root=INFO

# Optionally, set log level for your classes
logging.level.com.ska.telescopeSimulator=DEBUG

# Set log file location (optional)
logging.file.name=logs/application.log


server.port=8080
